ADDED numeric converter
vivipolli/python-flask pull request #1
Opened 2019-05-24 02:56 UTC by vivipolli

### Descrição
Segue [README](https://github.com/vivipolli/python-flask/blob/master/README.md)

### Imagem
Para fazer pull da imagem localmente do dockerHub e rodar o servidor: 
```
$ docker pull vivipolli/python_int_to_words
```

2019-05-24 12:18 UTC, edpessoa commented on app/extenso.py
> +        "dezesseis", "dezesete", "dezoito", "dezenove")
Typo: dezessete.

2019-05-28 18:29 UTC, m4rcelofs requested changes

2019-05-28 18:29 UTC, m4rcelofs commented on README.md
> +$ curl http://localhost:3000/-1042
nitpick: a porta padrão n é a 5050?

2019-05-28 18:29 UTC, m4rcelofs commented on README.md
> +## Criando o código
Geralmente o README se limita a descrever como configurar/rodar, não necessariamente a explicar o código (IMO o código deveria ser auto-explicativo, ou ter comentários inline)

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +    elif num < 0:
esse `elif` parece desnecessário

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +        result = "menos " + unid[num]
possivelmente não seja o melhor local pra colocar o `menos`

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +    if num < 0:
mesma coisa - ficou um copy/paste do código em vários lugares, pra versão negativo e pra versão positivo

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +                tpl = two_numbers(a)
também parece ter coisas repetidas nesses `if`s internos

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +    return result
faltou um "=" em algum lugar aí, hehe

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +            result = tpl + " mil" + " e " + c
tem um bug aqui

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +          "seicentos", "setecentos", "oitocentos", "novecentos"]
typo: seiscentos

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +centen = ["", "cem", "duzentos", "trezentos", "quatrocentos", "quinhentos",
o "cem" vale pra todos os casos?

2019-05-28 18:29 UTC, m4rcelofs commented on app/extenso.py
> +    elif 20 <= num <= 99 or -99 <= num <= -20:
o -20 n tá passando por aqui

2019-05-28 18:53 UTC, vivipolli commented on README.md
> +$ curl http://localhost:3000/-1042
sim sim, usei 5050 no código e esqueci de atualizar aqui

2019-05-28 19:02 UTC, vivipolli commented on app/extenso.py
> +centen = ["", "cem", "duzentos", "trezentos", "quatrocentos", "quinhentos",
desculpe, não entendi

2019-05-28 19:02 UTC, vivipolli commented on app/extenso.py
> +    elif 20 <= num <= 99 or -99 <= num <= -20:
vou atualizar

2019-05-28 19:33 UTC, vivipolli commented on app/extenso.py
> +        result = "menos " + unid[num]
coloquei na última função

2019-05-28 19:41 UTC, vivipolli commented on app/extenso.py
> +            result = tpl + " mil" + " e " + c
removi o "e"

2019-05-28 19:54 UTC, m4rcelofs commented on app/extenso.py
> +centen = ["", "cem", "duzentos", "trezentos", "quatrocentos", "quinhentos",
101, 111...

2019-05-28 20:14 UTC, vivipolli commented on app/extenso.py
> +centen = ["", "cem", "duzentos", "trezentos", "quatrocentos", "quinhentos",
tem razão, faltou o "cento", atualizado já:
```python
centen = ["cem", "cento", "duzentos", "trezentos", "quatrocentos", "quinhentos"(...)
```


```python
def three_numbers(num):
    if num % 100 == 0:
        a = num // 100
        result = centen[0] 
```

2019-05-28 20:26 UTC, vivipolli commented on app/extenso.py
> +centen = ["", "cem", "duzentos", "trezentos", "quatrocentos", "quinhentos",
Tem razão, alterei pra "cento" e coloquei o "cem" no código:
```python
def three_numbers(num):
    if num % 100 == 0:
        if num == 100: 
            result = "cem"
        else:
            a = num // 100
            result = centen[a]
```

2019-05-28 20:50 UTC, m4rcelofs commented
Tens como atualizar a imagem no dockerhub pra eu rodar os testes de novo, pfv?

2019-05-28 21:19 UTC, vivipolli commented
> Tens como atualizar a imagem no dockerhub pra eu rodar os testes de novo, pfv?
Claro, acabei de fazer um novo push lá:
https://hub.docker.com/r/vivipolli/python_int_to_words/tags

2019-09-22 14:40 UTC, merged